movieproject/movieapp/urls.py
from django.urls import path
from movieapp import views
app_name = 'movieapp'
#namespaceing - mention the folder also

urlpatterns = [
    path('', views.index, name="index"),
    path('movie/<int:movie_id>/', views.detail, name='detail'),
    path('add/',views.add_movie, name='add_movie'),
    path('update/<int:id>/', views.update, name='update'),
    path('delete/<int:id>/', views.delete, name='delete'),
]

movieproject/movieproject/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from movieproject import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('movieapp.urls'))
]

if settings.DEBUG :
    urlpatterns += static (settings.STATIC_URL,
                           document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

movieproject/movieapp/models.py
from django.db import models

# Create your models here.
class table_movie(models.Model):
    name = models.CharField(max_length=200)
    desc = models.TextField()
    year = models.IntegerField()
    img = models.ImageField(upload_to='gallery')

    def __str__(self):
        return self.name

movieproject/movieapp/forms.py
from django import forms
from .models import table_movie


class Movie_form(forms.ModelForm):
    class Meta:
        model = table_movie
        fields = ['name', 'desc', 'year', 'img']

movieproject/movieapp/views.py
from django.shortcuts import render, redirect
from . forms import Movie_form
from . models import table_movie

# Create your views here.
def index(request):
    obj = table_movie.objects.all()
    context = {
        'movie_list': obj
    }
    return render(request, 'index.html', context)

def detail(request,movie_id):
    obj_movie = table_movie.objects.get(id=movie_id)
    return render(request,'detail.html', {'key1':obj_movie})
def add_movie(request):
    if request.method == 'POST':
        name = request.POST.get("name")
        desc = request.POST.get("desc")
        year = request.POST.get("year")
        img = request.FILES["img"]
        movie = table_movie(name=name, desc=desc, year=year, img=img)
        movie.save()
        return redirect('/')
    return render(request, "add.html")
def update(request, id):
    old = table_movie.objects.get(id=id)
    my_form = Movie_form(request.POST or None, request.FILES, instance=old)
    if my_form.is_valid():
        my_form.save()
        return redirect('/')
    return render(request, 'edit.html', {'key_form':my_form, 'key_name':old})
def delete(request, id):
    if request.method == "POST":
        movie = table_movie.objects.get(id=id)
        movie.delete()
        return redirect('/')
    return render(request, 'delete.html')

movieproject/templates/add.html
{% extends 'base.html' %}
{% block body %}

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <table cellpadding="10" >
        <tr> <th> <u> ADD NEW MOVIE </u> </th></tr>
    <tr> <td><input type="text" name="name" placeholder="movie name"> </td></tr>
    <tr> <td><input type="text" name="desc" placeholder="movie desc"> </td></tr>
    <tr> <td><input type="text" name="year" placeholder="movie year"> </td></tr>
    <tr> <td><input type="file" name="img" > </td></tr>
    <tr> <td><input type="submit" > </td></tr>
    </table>
</form>
{% endblock %}

movieproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>index</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<!-- As a heading -->
<nav class="navbar navbar-dark bg-dark">
  <span class="navbar-brand mb-0 h1">Online Movie Store </span> 
    <div class="nav-item">
        <a class="nav-link btn btn-outline-success my-2" href="{% url 'movieapp:add_movie' %}">Add Movie</a>
  </div>
</nav> <br>
<div class="container">
{% block body %}
{% endblock %}
</div>
</body>
</html>

movieproject/templates/delete.html
{% extends 'base.html' %}
{% block body %}
<form method="POST">
  {% csrf_token %}
  <h3>Are you sure?</h3>
  <input type="submit" value="DELETE">
</form>
{% endblock %}

movieproject/templates/detail.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
<div class="row">
<div class="col-md-6 "  style="margin:30px;">
    <img class="center" src="{{key1.img.url}}" style="width:200px; height:300px; object-fit:scale-down;">
</div>
<div class="col-md-6">
    <h4>{{key1.name}} </h4>
    <h5>{{key1.desc}}</h5>
    <h6>Year : {{key1.year}}</h6>
    <a class="btn btn-success border" href="{% url 'movieapp:update' key1.id %}"> UPDATE-MOVIE</a>
    <a class="btn btn-warning border" href="{% url 'movieapp:delete' key1.id %}">  DELETE-MOVIE </a>

</div>
</div>
</div>
{% endblock %}

movieproject/templates/edit.html
{% extends 'base.html' %}
{% block body %}

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ key_form.as_p}}  <br>
    <input type="submit" value="SUBMIT">
</form>
{% endblock %}

movieproject/templates/index.html
{% extends 'base.html' %}
{% block body %}
<div class="row">
    {% for i in movie_list %}
    <div class="col-md-3" style="margin:10px;">
        <div class="card" style="width:18rem; padding:10px;">
            <img class="card-img-top mx-auto d-block" src="{{i.img.url}}" style="width:250px; height:300px; object-fit:scale-down;">
            <div class="card-body">
            <h5 class="card-title text-center mt-10">
                <a href="{% url 'movieapp:detail' i.id %}" class="btn btn-primary"> {{i.name}} </a>
            </h5>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}